apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso1920-file-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso1920-file-storage
  template:
    metadata:
      labels:
        app: rso1920-file-storage
    spec:
      containers:
        - image: rso1920/filestorage:withoutAWSCredentials
          name: rso1920-file-storage
          env:
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://10.0.8.185:8081
            - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
              value: http://etcd:2379/health
            - name: KUMULUZEE_GRPC_SERVER_URL
              value: 10.0.8.185
          ports:
            - containerPort: 8081
              name: file-storage
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: file-storage
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: file-storage
            initialDelaySeconds: 60
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: rso1920-file-storage
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: file-storage
  selector:
    app: rso1920-file-storage
